### ISSUE TITLE
Deprecated Azure Blob Storage Library is used

### ISSUE THREAD

**Issue by AndiHahn** [SyncfusionExamples/ej2-azure-aspcore-file-provider#14]
The implementation uses a deprecated library for accessing Azure Blob Storage (WindowsAzure.Storage).
The latest package which should be used is Azure.Storage.Blobs 
https://www.nuget.org/packages/Azure.Storage.Blobs/

Are you planning to change the library to the current one?

**Comment by thirukumaran-murugan** [comment]
Hi @AndiHahn 

Greetings from Syncfusion support.

We have validated your reported query in the File Manager component. Please find the details below.

Currently, we are using WindowsAzure.Storage deprecated package for our Azure file service provider. However, updating the Azure service has already been considered as a feature and this will be included in our Volume 3 SP release which is expected to be rolled out by the month of November 2021. You can track the status through the below link.
 
https://www.syncfusion.com/feedback/18954/need-to-update-the-azure-service-for-filemanager-component
 
However, as of now, we suggest you install the above package.

Please let us know if you need any further assistance.

Regards,
Thirukumaran M.
